
export default {
    LOGIN_ACTION: "LOGIN_ACTION",
    TOURNAMENT_LIST: "TOURNAMENT_LIST",
    TOURNAMENT_FIND: "TOURNAMENT_FIND",
    TOURNAMENT_ADD: "TOURNAMENT_ADD",
    ERROR_500: "ERROR_500",
    TOURNAMENT_LIST_UPCOMING: "TOURNAMENT_LIST_UPCOMING",
    TOURNAMENT_LIST_OLDER: "TOURNAMENT_LIST_OLDER",
    PLAYER_ADD: "PLAYER_ADD",
    ADD_USER: "ADD_USER",
    STATES_LIST:"STATES_LIST",
    DISTICTS_LIST:"DISTICTS_LIST"    
}